# -*- coding: utf-8 -*-
"""LeetCodeProblems.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EhXHTo5IVZOHKp27uxh1iG6lWh_PX7WG
"""

class Solution(object):
    def bestSolution_reverseWords(self, s):
        """
        :type s: str
        :rtype: str
        """
        strng = s.split(" ")
        new_str = []
        for item in strng:
            new_str.append(item[::-1])
        return " ".join(new_str)

    def mySolution_reverseWords(self, s):
            """
            :type s: str
            :rtype: str
            """
            output = ""
            words = s.split()
            for i in range(len(words)):
                temp = ""
                for j in range(len(words[i])):
                    temp = words[i][j] + temp
                if i == len(words) - 1:
                    output += temp
                else:
                    output += temp + " "
            return output